version: '3.8'

x-geonetwork-environment:
  &default-geonetwork-environment
  WEBAPP_CONTEXT_PATH: /geonetwork
  DATA_DIR: /catalogue-data

  JAVA_OPTS: >-
    -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
    -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
    -Djetty.httpConfig.requestHeaderSize=32768
    -Dorg.eclipse.jetty.server.Request.maxFormContentSize=500000
    -Dorg.eclipse.jetty.server.Request.maxFormKeys=4000
  # For remote debug
  # -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005

  GN_CONFIG_PROPERTIES: >-
    -Dgeonetwork.dir=/catalogue-data
    -Dgeonetwork.formatter.dir=/catalogue-data/data/formatter
    -Dgeonetwork.schema.dir=/opt/geonetwork/WEB-INF/data/config/schema_plugins
    -Dgeonetwork.indexConfig.dir=/opt/geonetwork/WEB-INF/data/config/index
    -Des.host=elasticsearch
    -Des.protocol=http
    -Des.port=9200
    -Des.url=http://elasticsearch:9200
    -Des.username=
    -Des.password=
    -Dgeonetwork.ESFeaturesProxy.targetUri=http://elasticsearch:9200/gn-features/{_}
    -Dgeonetwork.HttpDashboardProxy.targetUri=http://kibana:5601
    -Dgeonetwork.MicroServicesProxy.targetUri=http://ogc-api-records-service:8080

  GEONETWORK_DB_TYPE: postgres
  GEONETWORK_DB_HOST: database
  GEONETWORK_DB_PORT: 5432
  GEONETWORK_DB_NAME: geonetwork
  GEONETWORK_DB_USERNAME: geonetwork
  GEONETWORK_DB_PASSWORD: geonetwork


x-service-geonetwork:
  &default-service-geonetwork
  image: geonetwork:4.4.0
  restart: always
  ports:
    - 8080:8080
  volumes:
    - geonetwork:/catalogue-data
  depends_on:
    - elasticsearch
    - database
  networks:
    - gn-network


volumes:
  geonetwork:
  esdata:
  pgdata:
  pglog:
  nginxlog:
  apachelog:


networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx
    ports:
      - 80:80
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=localhost
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
      - WEBAPP_CONTEXT_PATH=/geonetwork

    volumes:
      - ./nginx:/etc/nginx/templates
      - nginxlog:/var/log/nginx
    depends_on:
      - geonetwork
    networks:
      - gn-network

#  www:
#    image: httpd
#    ports:
#      - 81:80
#    environment:
#      - WEBAPP_CONTEXT_PATH=/geonetwork
#    volumes:
#      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./apache/gn-httpd.conf:/usr/local/apache2/conf/gn-httpd.conf
#      - apachelog:/usr/local/apache2/logs
#    depends_on:
#      - geonetwork
#    networks:
#      - gn-network


  database:
    image: postgis/postgis:11-2.5
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - gn-network

  geonetwork:
    <<: *default-service-geonetwork
    environment:
      <<: *default-geonetwork-environment


  ogc-api-records-service:
    image: geonetwork/gn-cloud-ogc-api-records-service:4.2.5-0
    environment:
      SPRING_PROFILES_ACTIVE: standalone
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/geonetwork
      SPRING_DATASOURCE_USERNAME: geonetwork
      SPRING_DATASOURCE_PASSWORD: geonetwork
      GN_BASEURL: http://geonetwork:8080/geonetwork/api
      GN_LEGACY_URL: http://geonetwork:8080/geonetwork
      GN_INDEX_URL: http://elasticsearch:9200
      SERVER_FORWARDHEADERSSTRATEGY: FRAMEWORK
      JAVA_OPTS: -Dfile.encoding=UTF-8

    depends_on:
      - database
      - elasticsearch
      - geonetwork
    networks:
      - gn-network




  elasticsearch:
    image: elasticsearch:7.17.10
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gn-network

  kibana:
    image: kibana:7.17.10
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-network
