FROM geonetwork:4.4.8

ARG GN_VERSION=4.4.8
ARG PLUGIN_DOWNLOAD_URL="https://sourceforge.net/projects/geonetwork/files/GeoNetwork_opensource/v${GN_VERSION}/gn-datahub-integration-${GN_VERSION}-0.zip/download"

RUN curl -fSL -o /tmp/gn-plugin-datahub-integration.zip ${PLUGIN_DOWNLOAD_URL} \
    && unzip /tmp/gn-plugin-datahub-integration.zip -d /tmp/plugin \
    && cp /tmp/plugin/gn-datahub-integration-${GN_VERSION}-0/lib/*.jar /opt/geonetwork/WEB-INF/lib/ \
    && rm -rf /tmp/plugin /tmp/gn-plugin-datahub-integration.zip
